[versions]
activityComposeVersion = "1.11.0"
appcompatVersion = "1.7.1"
coilComposeVersion = "3.3.0"
composeBomVersion = "2025.10.00"
constraintLayoutVersion = "2.2.1"
coreKtxVersion = "1.17.0"
coreSplashscreenVersion = "1.0.1"
documentFileVersion = "1.1.0"
espressoCoreVersion = "3.7.0"
gradleVersion = "8.13.0"
junitVersion = "4.13.2"
kotlinVersion = "2.2.20"
coroutinesAndroidVersion = "1.10.2"
coroutinesCoreVersion = "1.10.2"
lifecycleCommonJava8Version = "2.9.4"
lifecycleViewmodelComposeVersion = "2.9.4"
materialVersion = "1.13.0"
multidexVersion = "2.0.1"
preferenceKtxVersion = "1.2.1"
roomVersion = "2.8.2"
testRunnerVersion = "1.7.0"
kspVersion = "2.2.20-2.0.3"

[libraries]
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityComposeVersion" }
adaptive = { module = "androidx.compose.material3.adaptive:adaptive" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilComposeVersion" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "composeBomVersion" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayoutVersion" }
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreenVersion" }
documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentFileVersion" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCoreVersion" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradleVersion" }
junit = { module = "junit:junit", version.ref = "junitVersion" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinVersion" }
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinVersion" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutinesAndroidVersion" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutinesCoreVersion" }
lifecycle-service = { module = "androidx.lifecycle:lifecycle-service", version.ref = "lifecycleCommonJava8Version" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycleViewmodelComposeVersion" }
material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
material-icons-core = { module = "androidx.compose.material:material-icons-core" }
material3 = { module = "androidx.compose.material3:material3" }
multidex = { module = "androidx.multidex:multidex", version.ref = "multidexVersion" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtxVersion" }
material = { module = "com.google.android.material:material", version.ref = "materialVersion" }
room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
runner = { module = "androidx.test:runner", version.ref = "testRunnerVersion" }
ui-test-manifest = { module = "androidx.compose.ui:ui-test-manifest" }
ui-test-junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlinVersion" }
ksp = { id = "com.google.devtools.ksp", version.ref = "kspVersion" }